name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2022

    steps:
      - name: Setup Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
        with:
          sdk-version: 18362

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: MSBuild
        #working-directory: Source
        #run: msbuild MQTTnet.sln /t:Clean /t:Restore /t:Build /p:Configuration="Release" /p:FileVersion=$assemblyVersion /p:AssemblyVersion=$assemblyVersion /p:PackageVersion=$nugetVersion /verbosity:m
        run: msbuild MQTTnet.sln /t:Clean /t:Restore /t:Build /p:Configuration="Release" /verbosity:m

      - name: Core Tests
        run: vstest.console.exe /Platform:x64 .\Tests\MQTTnet.Core.Tests\MQTTnet.Tests.csproj

      - name: ASP.NET Tests
        run: vstest.console.exe /Platform:x64 .\Tests\MQTTnet.AspNetCore.Tests\MQTTnet.AspNetCore.Tests.csproj

    #  - name: Build
    #    shell: pwsh
    #    run: |
    #      Set-Location -Path "Build"
    #      .\build.ps1 1.2.3 4.5.6-rc1

      - name: Collect nuget Packages
        uses: actions/upload-artifact@v2
        with:
          name: nuget Packages
          path: |
            Source\**\bin\Release\*.nupkg
            Source\**\bin\Release\*.snupkg

#      - name: Install dependencies
#        run: dotnet restore MQTTnet.sln
#      - name: Build
#        run: dotnet build --configuration Release --no-restore MQTTnet.sln
#      - name: Test MQTTnet
#        run: dotnet test --no-restore --verbosity normal Tests\MQTTnet.Core.Tests\MQTTnet.Tests.csproj
#      - name: Test AspNetCore
#        run: dotnet test --no-restore --verbosity normal Tests\MQTTnet.AspNetCore.Tests\MQTTnet.AspNetCore.Tests.csproj