name: CI

on: [push]

env:
  ASSEMBLY_VERSION: "4.0.0"
  NUGET_VERSION: "4.0.0-preview2"

jobs:
  build:

    runs-on: windows-2022

    steps:
      - name: Setup Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
        with:
          sdk-version: 18362

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Checkout Code
        uses: actions/checkout@v2

 #     - name : Setup nuget
 #       uses: nuget/setup-nuget@v1
 #         with:
 #           nuget-api-key: ${{ secrets.NUGET_API_KEY }}
 #           nuget-version: '5.x'


      - name: Restore nuget packages
        run: msbuild .\MQTTnet.sln /t:Restore /p:Configuration="Release" /verbosity:m

      - name: Build MQTTnet core library
        run: msbuild .\Source\MQTTnet\MQTTnet.csproj /t:Build /p:Configuration="Release" /verbosity:m /p:FileVersion=${{ env.ASSEMBLY_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:PackageVersion=${{ env.NUGET_VERSION }}

      - name: Build Managed Client extension library
        run: msbuild .\Source\MQTTnet.Extensions.ManagedClient\MQTTnet.Extensions.ManagedClient.csproj /t:Build /p:Configuration="Release" /verbosity:m /p:FileVersion=${{ env.ASSEMBLY_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:PackageVersion=${{ env.NUGET_VERSION }}

      - name: Build RPC extension library
        run: msbuild .\Source\MQTTnet.Extensions.Rpc\MQTTnet.Extensions.Rpc.csproj /t:Build /p:Configuration="Release" /verbosity:m /p:FileVersion=${{ env.ASSEMBLY_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:PackageVersion=${{ env.NUGET_VERSION }}

      - name: Build WebSocket4Net extension library
        run: msbuild .\Source\MQTTnet.Extensions.WebSocket4Net\MQTTnet.Extensions.WebSocket4Net.csproj /t:Build /p:Configuration="Release" /verbosity:m /p:FileVersion=${{ env.ASSEMBLY_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:PackageVersion=${{ env.NUGET_VERSION }}

      - name: Build ASP.NET Core extension library
        run: msbuild .\Source\MQTTnet.AspNetCore\MQTTnet.AspNetCore.csproj /t:Build /p:Configuration="Release" /verbosity:m /p:FileVersion=${{ env.ASSEMBLY_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:PackageVersion=${{ env.NUGET_VERSION }}

      #- name: Core Tests
      #  run: vstest.console.exe /Platform:x64 .\Tests\MQTTnet.Core.Tests\MQTTnet.Tests.csproj

      #- name: ASP.NET Tests
      #  run: vstest.console.exe /Platform:x64 .\Tests\MQTTnet.AspNetCore.Tests\MQTTnet.AspNetCore.Tests.csproj

    #  - name: Build
    #    shell: pwsh
    #    run: |
    #      Set-Location -Path "Build"
    #      .\build.ps1 1.2.3 4.5.6-rc1

      - name: Collect nuget Packages
        uses: actions/upload-artifact@v2
        with:
          name: nuget Packages
          path: |
            **\*.nupkg
            **\*.snupkg

#      - name: Install dependencies
#        run: dotnet restore MQTTnet.sln
#      - name: Build
#        run: dotnet build --configuration Release --no-restore MQTTnet.sln
#      - name: Test MQTTnet
#        run: dotnet test --no-restore --verbosity normal Tests\MQTTnet.Core.Tests\MQTTnet.Tests.csproj
#      - name: Test AspNetCore
#        run: dotnet test --no-restore --verbosity normal Tests\MQTTnet.AspNetCore.Tests\MQTTnet.AspNetCore.Tests.csproj